<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class CitiesSeeder extends Seeder
{
    public function run()
    {
        $cities = [
            // Aceh
            ['id_province' => 1, 'city_name' => 'Banda Aceh'],
            ['id_province' => 1, 'city_name' => 'Langsa'],
            ['id_province' => 1, 'city_name' => 'Lhokseumawe'],
            ['id_province' => 1, 'city_name' => 'Sabang'],
            ['id_province' => 1, 'city_name' => 'Subulussalam'],
            ['id_province' => 1, 'city_name' => 'Aceh Barat'],
            ['id_province' => 1, 'city_name' => 'Aceh Barat Daya'],
            ['id_province' => 1, 'city_name' => 'Aceh Besar'],
            ['id_province' => 1, 'city_name' => 'Aceh Jaya'],
            ['id_province' => 1, 'city_name' => 'Aceh Selatan'],
            ['id_province' => 1, 'city_name' => 'Aceh Singkil'],
            ['id_province' => 1, 'city_name' => 'Aceh Tamiang'],
            ['id_province' => 1, 'city_name' => 'Aceh Tengah'],
            ['id_province' => 1, 'city_name' => 'Aceh Tenggara'],
            ['id_province' => 1, 'city_name' => 'Aceh Timur'],
            ['id_province' => 1, 'city_name' => 'Aceh Utara'],
            ['id_province' => 1, 'city_name' => 'Bener Meriah'],
            ['id_province' => 1, 'city_name' => 'Bireuen'],
            ['id_province' => 1, 'city_name' => 'Gayo Lues'],
            ['id_province' => 1, 'city_name' => 'Nagan Raya'],
            ['id_province' => 1, 'city_name' => 'Pidie'],
            ['id_province' => 1, 'city_name' => 'Pidie Jaya'],
            ['id_province' => 1, 'city_name' => 'Simeulue'],

            // Sumatera Utara
            ['id_province' => 2, 'city_name' => 'Medan'],
            ['id_province' => 2, 'city_name' => 'Binjai'],
            ['id_province' => 2, 'city_name' => 'Tebing Tinggi'],
            ['id_province' => 2, 'city_name' => 'Pematang Siantar'],
            ['id_province' => 2, 'city_name' => 'Tanjungbalai'],
            ['id_province' => 2, 'city_name' => 'Sibolga'],
            ['id_province' => 2, 'city_name' => 'Padangsidimpuan'],
            ['id_province' => 2, 'city_name' => 'Gunungsitoli'],
            ['id_province' => 2, 'city_name' => 'Asahan'],
            ['id_province' => 2, 'city_name' => 'Batubara'],
            ['id_province' => 2, 'city_name' => 'Dairi'],
            ['id_province' => 2, 'city_name' => 'Deli Serdang'],
            ['id_province' => 2, 'city_name' => 'Humbang Hasundutan'],
            ['id_province' => 2, 'city_name' => 'Karo'],
            ['id_province' => 2, 'city_name' => 'Labuhanbatu'],
            ['id_province' => 2, 'city_name' => 'Labuhanbatu Selatan'],
            ['id_province' => 2, 'city_name' => 'Labuhanbatu Utara'],
            ['id_province' => 2, 'city_name' => 'Langkat'],
            ['id_province' => 2, 'city_name' => 'Mandailing Natal'],
            ['id_province' => 2, 'city_name' => 'Nias'],
            ['id_province' => 2, 'city_name' => 'Nias Barat'],
            ['id_province' => 2, 'city_name' => 'Nias Selatan'],
            ['id_province' => 2, 'city_name' => 'Nias Utara'],
            ['id_province' => 2, 'city_name' => 'Pakpak Bharat'],
            ['id_province' => 2, 'city_name' => 'Samosir'],
            ['id_province' => 2, 'city_name' => 'Serdang Bedagai'],
            ['id_province' => 2, 'city_name' => 'Simalungun'],
            ['id_province' => 2, 'city_name' => 'Tapanuli Selatan'],
            ['id_province' => 2, 'city_name' => 'Tapanuli Tengah'],
            ['id_province' => 2, 'city_name' => 'Tapanuli Utara'],
            ['id_province' => 2, 'city_name' => 'Toba'],

            // Sumatera Barat
            ['id_province' => 3, 'city_name' => 'Padang'],
            ['id_province' => 3, 'city_name' => 'Bukittinggi'],
            ['id_province' => 3, 'city_name' => 'Padangpanjang'],
            ['id_province' => 3, 'city_name' => 'Pariaman'],
            ['id_province' => 3, 'city_name' => 'Payakumbuh'],
            ['id_province' => 3, 'city_name' => 'Sawahlunto'],
            ['id_province' => 3, 'city_name' => 'Solok'],
            ['id_province' => 3, 'city_name' => 'Agam'],
            ['id_province' => 3, 'city_name' => 'Dharmasraya'],
            ['id_province' => 3, 'city_name' => 'Kepulauan Mentawai'],
            ['id_province' => 3, 'city_name' => 'Lima Puluh Kota'],
            ['id_province' => 3, 'city_name' => 'Pasaman'],
            ['id_province' => 3, 'city_name' => 'Pasaman Barat'],
            ['id_province' => 3, 'city_name' => 'Pesisir Selatan'],
            ['id_province' => 3, 'city_name' => 'Sijunjung'],
            ['id_province' => 3, 'city_name' => 'Solok Selatan'],
            ['id_province' => 3, 'city_name' => 'Tanah Datar'],

            // Riau
            ['id_province' => 4, 'city_name' => 'Pekanbaru'],
            ['id_province' => 4, 'city_name' => 'Dumai'],
            ['id_province' => 4, 'city_name' => 'Bengkalis'],
            ['id_province' => 4, 'city_name' => 'Indragiri Hilir'],
            ['id_province' => 4, 'city_name' => 'Indragiri Hulu'],
            ['id_province' => 4, 'city_name' => 'Kampar'],
            ['id_province' => 4, 'city_name' => 'Kepulauan Meranti'],
            ['id_province' => 4, 'city_name' => 'Kuantan Singingi'],
            ['id_province' => 4, 'city_name' => 'Pelalawan'],
            ['id_province' => 4, 'city_name' => 'Rokan Hilir'],
            ['id_province' => 4, 'city_name' => 'Rokan Hulu'],
            ['id_province' => 4, 'city_name' => 'Siak'],

            // Jambi
            ['id_province' => 5, 'city_name' => 'Jambi'],
            ['id_province' => 5, 'city_name' => 'Sungai Penuh'],
            ['id_province' => 5, 'city_name' => 'Batanghari'],
            ['id_province' => 5, 'city_name' => 'Bungo'],
            ['id_province' => 5, 'city_name' => 'Kerinci'],
            ['id_province' => 5, 'city_name' => 'Merangin'],
            ['id_province' => 5, 'city_name' => 'Muaro Jambi'],
            ['id_province' => 5, 'city_name' => 'Sarolangun'],
            ['id_province' => 5, 'city_name' => 'Tanjung Jabung Barat'],
            ['id_province' => 5, 'city_name' => 'Tanjung Jabung Timur'],
            ['id_province' => 5, 'city_name' => 'Tebo'],

            // Sumatera Selatan
            ['id_province' => 6, 'city_name' => 'Palembang'],
            ['id_province' => 6, 'city_name' => 'Lubuklinggau'],
            ['id_province' => 6, 'city_name' => 'Pagar Alam'],
            ['id_province' => 6, 'city_name' => 'Prabumulih'],
            ['id_province' => 6, 'city_name' => 'Banyuasin'],
            ['id_province' => 6, 'city_name' => 'Empat Lawang'],
            ['id_province' => 6, 'city_name' => 'Lahat'],
            ['id_province' => 6, 'city_name' => 'Muara Enim'],
            ['id_province' => 6, 'city_name' => 'Musi Banyuasin'],
            ['id_province' => 6, 'city_name' => 'Musi Rawas'],
            ['id_province' => 6, 'city_name' => 'Ogan Ilir'],
            ['id_province' => 6, 'city_name' => 'Ogan Komering Ilir'],
            ['id_province' => 6, 'city_name' => 'Ogan Komering Ulu'],
            ['id_province' => 6, 'city_name' => 'Ogan Komering Ulu Selatan'],
            ['id_province' => 6, 'city_name' => 'Ogan Komering Ulu Timur'],
            ['id_province' => 6, 'city_name' => 'Penukal Abab Lematang Ilir'],

            // Bengkulu
            ['id_province' => 7, 'city_name' => 'Bengkulu'],
            ['id_province' => 7, 'city_name' => 'Bengkulu Selatan'],
            ['id_province' => 7, 'city_name' => 'Bengkulu Tengah'],
            ['id_province' => 7, 'city_name' => 'Bengkulu Utara'],
            ['id_province' => 7, 'city_name' => 'Kaur'],
            ['id_province' => 7, 'city_name' => 'Kepahiang'],
            ['id_province' => 7, 'city_name' => 'Lebong'],
            ['id_province' => 7, 'city_name' => 'Mukomuko'],
            ['id_province' => 7, 'city_name' => 'Rejang Lebong'],
            ['id_province' => 7, 'city_name' => 'Seluma'],

            // Lampung
            ['id_province' => 8, 'city_name' => 'Bandar Lampung'],
            ['id_province' => 8, 'city_name' => 'Metro'],
            ['id_province' => 8, 'city_name' => 'Lampung Barat'],
            ['id_province' => 8, 'city_name' => 'Lampung Selatan'],
            ['id_province' => 8, 'city_name' => 'Lampung Tengah'],
            ['id_province' => 8, 'city_name' => 'Lampung Timur'],
            ['id_province' => 8, 'city_name' => 'Lampung Utara'],
            ['id_province' => 8, 'city_name' => 'Mesuji'],
            ['id_province' => 8, 'city_name' => 'Pesawaran'],
            ['id_province' => 8, 'city_name' => 'Pringsewu'],
            ['id_province' => 8, 'city_name' => 'Tanggamus'],
            ['id_province' => 8, 'city_name' => 'Tulang Bawang'],
            ['id_province' => 8, 'city_name' => 'Tulang Bawang Barat'],
            ['id_province' => 8, 'city_name' => 'Way Kanan'],

            // Kepulauan Bangka Belitung
            ['id_province' => 9, 'city_name' => 'Pangkal Pinang'],
            ['id_province' => 9, 'city_name' => 'Bangka'],
            ['id_province' => 9, 'city_name' => 'Bangka Barat'],
            ['id_province' => 9, 'city_name' => 'Bangka Selatan'],
            ['id_province' => 9, 'city_name' => 'Bangka Tengah'],
            ['id_province' => 9, 'city_name' => 'Belitung'],
            ['id_province' => 9, 'city_name' => 'Belitung Timur'],

            // Kepulauan Riau
            ['id_province' => 10, 'city_name' => 'Batam'],
            ['id_province' => 10, 'city_name' => 'Tanjung Pinang'],
            ['id_province' => 10, 'city_name' => 'Bintan'],
            ['id_province' => 10, 'city_name' => 'Karimun'],
            ['id_province' => 10, 'city_name' => 'Kepulauan Anambas'],
            ['id_province' => 10, 'city_name' => 'Lingga'],
            ['id_province' => 10, 'city_name' => 'Natuna'],

            // DKI Jakarta
            ['id_province' => 11, 'city_name' => 'Jakarta Pusat'],
            ['id_province' => 11, 'city_name' => 'Jakarta Utara'],
            ['id_province' => 11, 'city_name' => 'Jakarta Barat'],
            ['id_province' => 11, 'city_name' => 'Jakarta Timur'],
            ['id_province' => 11, 'city_name' => 'Jakarta Selatan'],

            // Jawa Barat
            ['id_province' => 12, 'city_name' => 'Bandung'],
            ['id_province' => 12, 'city_name' => 'Bekasi'],
            ['id_province' => 12, 'city_name' => 'Bogor'],
            ['id_province' => 12, 'city_name' => 'Cimahi'],
            ['id_province' => 12, 'city_name' => 'Depok'],
            ['id_province' => 12, 'city_name' => 'Sukabumi'],
            ['id_province' => 12, 'city_name' => 'Tasikmalaya'],
            ['id_province' => 12, 'city_name' => 'Bandung Barat'],
            ['id_province' => 12, 'city_name' => 'Ciamis'],
            ['id_province' => 12, 'city_name' => 'Cianjur'],
            ['id_province' => 12, 'city_name' => 'Cirebon'],
            ['id_province' => 12, 'city_name' => 'Garut'],
            ['id_province' => 12, 'city_name' => 'Indramayu'],
            ['id_province' => 12, 'city_name' => 'Karawang'],
            ['id_province' => 12, 'city_name' => 'Kuningan'],
            ['id_province' => 12, 'city_name' => 'Majalengka'],
            ['id_province' => 12, 'city_name' => 'Pangandaran'],
            ['id_province' => 12, 'city_name' => 'Purwakarta'],
            ['id_province' => 12, 'city_name' => 'Subang'],
            ['id_province' => 12, 'city_name' => 'Sumedang'],

            // Jawa Tengah
            ['id_province' => 13, 'city_name' => 'Semarang'],
            ['id_province' => 13, 'city_name' => 'Magelang'],
            ['id_province' => 13, 'city_name' => 'Pekalongan'],
            ['id_province' => 13, 'city_name' => 'Salatiga'],
            ['id_province' => 13, 'city_name' => 'Surakarta'],
            ['id_province' => 13, 'city_name' => 'Tegal'],
            ['id_province' => 13, 'city_name' => 'Banjarnegara'],
            ['id_province' => 13, 'city_name' => 'Banyumas'],
            ['id_province' => 13, 'city_name' => 'Batang'],
            ['id_province' => 13, 'city_name' => 'Blora'],
            ['id_province' => 13, 'city_name' => 'Boyolali'],
            ['id_province' => 13, 'city_name' => 'Brebes'],
            ['id_province' => 13, 'city_name' => 'Cilacap'],
            ['id_province' => 13, 'city_name' => 'Demak'],
            ['id_province' => 13, 'city_name' => 'Grobogan'],
            ['id_province' => 13, 'city_name' => 'Jepara'],
            ['id_province' => 13, 'city_name' => 'Karanganyar'],
            ['id_province' => 13, 'city_name' => 'Kebumen'],
            ['id_province' => 13, 'city_name' => 'Kendal'],
            ['id_province' => 13, 'city_name' => 'Klaten'],
            ['id_province' => 13, 'city_name' => 'Kudus'],
            ['id_province' => 13, 'city_name' => 'Magelang'],
            ['id_province' => 13, 'city_name' => 'Pati'],
            ['id_province' => 13, 'city_name' => 'Pekalongan'],
            ['id_province' => 13, 'city_name' => 'Pemalang'],
            ['id_province' => 13, 'city_name' => 'Purbalingga'],
            ['id_province' => 13, 'city_name' => 'Purworejo'],
            ['id_province' => 13, 'city_name' => 'Rembang'],
            ['id_province' => 13, 'city_name' => 'Semarang'],
            ['id_province' => 13, 'city_name' => 'Sragen'],
            ['id_province' => 13, 'city_name' => 'Sukoharjo'],
            ['id_province' => 13, 'city_name' => 'Tegal'],
            ['id_province' => 13, 'city_name' => 'Temanggung'],
            ['id_province' => 13, 'city_name' => 'Wonogiri'],
            ['id_province' => 13, 'city_name' => 'Wonosobo'],

            // DI Yogyakarta
            ['id_province' => 14, 'city_name' => 'Yogyakarta'],
            ['id_province' => 14, 'city_name' => 'Bantul'],
            ['id_province' => 14, 'city_name' => 'Gunung Kidul'],
            ['id_province' => 14, 'city_name' => 'Kulon Progo'],
            ['id_province' => 14, 'city_name' => 'Sleman'],

            // Jawa Timur
            ['id_province' => 15, 'city_name' => 'Surabaya'],
            ['id_province' => 15, 'city_name' => 'Batu'],
            ['id_province' => 15, 'city_name' => 'Blitar'],
            ['id_province' => 15, 'city_name' => 'Kediri'],
            ['id_province' => 15, 'city_name' => 'Madiun'],
            ['id_province' => 15, 'city_name' => 'Malang'],
            ['id_province' => 15, 'city_name' => 'Mojokerto'],
            ['id_province' => 15, 'city_name' => 'Pasuruan'],
            ['id_province' => 15, 'city_name' => 'Probolinggo'],
            ['id_province' => 15, 'city_name' => 'Bangkalan'],
            ['id_province' => 15, 'city_name' => 'Banyuwangi'],
            ['id_province' => 15, 'city_name' => 'Blitar'],
            ['id_province' => 15, 'city_name' => 'Bojonegoro'],
            ['id_province' => 15, 'city_name' => 'Bondowoso'],
            ['id_province' => 15, 'city_name' => 'Gresik'],
            ['id_province' => 15, 'city_name' => 'Jember'],
            ['id_province' => 15, 'city_name' => 'Jombang'],
            ['id_province' => 15, 'city_name' => 'Kediri'],
            ['id_province' => 15, 'city_name' => 'Lamongan'],
            ['id_province' => 15, 'city_name' => 'Lumajang'],
            ['id_province' => 15, 'city_name' => 'Madiun'],
            ['id_province' => 15, 'city_name' => 'Magetan'],
            ['id_province' => 15, 'city_name' => 'Malang'],
            ['id_province' => 15, 'city_name' => 'Mojokerto'],
            ['id_province' => 15, 'city_name' => 'Nganjuk'],
            ['id_province' => 15, 'city_name' => 'Ngawi'],
            ['id_province' => 15, 'city_name' => 'Pacitan'],
            ['id_province' => 15, 'city_name' => 'Pamekasan'],
            ['id_province' => 15, 'city_name' => 'Pasuruan'],
            ['id_province' => 15, 'city_name' => 'Ponorogo'],
            ['id_province' => 15, 'city_name' => 'Probolinggo'],
            ['id_province' => 15, 'city_name' => 'Sampang'],
            ['id_province' => 15, 'city_name' => 'Sidoarjo'],
            ['id_province' => 15, 'city_name' => 'Situbondo'],
            ['id_province' => 15, 'city_name' => 'Sumenep'],
            ['id_province' => 15, 'city_name' => 'Trenggalek'],
            ['id_province' => 15, 'city_name' => 'Tuban'],
            ['id_province' => 15, 'city_name' => 'Tulungagung'],

            // Banten
            ['id_province' => 16, 'city_name' => 'Serang'],
            ['id_province' => 16, 'city_name' => 'Cilegon'],
            ['id_province' => 16, 'city_name' => 'Tangerang'],
            ['id_province' => 16, 'city_name' => 'South Tangerang'],
            ['id_province' => 16, 'city_name' => 'Lebak'],
            ['id_province' => 16, 'city_name' => 'Pandeglang'],
            ['id_province' => 16, 'city_name' => 'Serang'],
            ['id_province' => 16, 'city_name' => 'Tangerang'],

            // Bali
            ['id_province' => 17, 'city_name' => 'Denpasar'],
            ['id_province' => 17, 'city_name' => 'Badung'],
            ['id_province' => 17, 'city_name' => 'Bangli'],
            ['id_province' => 17, 'city_name' => 'Buleleng'],
            ['id_province' => 17, 'city_name' => 'Gianyar'],
            ['id_province' => 17, 'city_name' => 'Jembrana'],
            ['id_province' => 17, 'city_name' => 'Karangasem'],
            ['id_province' => 17, 'city_name' => 'Klungkung'],
            ['id_province' => 17, 'city_name' => 'Tabanan'],

            // Nusa Tenggara Barat
            ['id_province' => 18, 'city_name' => 'Mataram'],
            ['id_province' => 18, 'city_name' => 'Bima'],
            ['id_province' => 18, 'city_name' => 'Dompu'],
            ['id_province' => 18, 'city_name' => 'Lombok Barat'],
            ['id_province' => 18, 'city_name' => 'Lombok Tengah'],
            ['id_province' => 18, 'city_name' => 'Lombok Timur'],
            ['id_province' => 18, 'city_name' => 'Lombok Utara'],
            ['id_province' => 18, 'city_name' => 'Sumbawa'],
            ['id_province' => 18, 'city_name' => 'Sumbawa Barat'],

            // Nusa Tenggara Timur
            ['id_province' => 19, 'city_name' => 'Kupang'],
            ['id_province' => 19, 'city_name' => 'Alor'],
            ['id_province' => 19, 'city_name' => 'Belu'],
            ['id_province' => 19, 'city_name' => 'Ende'],
            ['id_province' => 19, 'city_name' => 'Flores Timur'],
            ['id_province' => 19, 'city_name' => 'Kupang'],
            ['id_province' => 19, 'city_name' => 'Lembata'],
            ['id_province' => 19, 'city_name' => 'Malaka'],
            ['id_province' => 19, 'city_name' => 'Manggarai'],
            ['id_province' => 19, 'city_name' => 'Manggarai Barat'],
            ['id_province' => 19, 'city_name' => 'Manggarai Timur'],
            ['id_province' => 19, 'city_name' => 'Nagekeo'],
            ['id_province' => 19, 'city_name' => 'Ngada'],
            ['id_province' => 19, 'city_name' => 'Rote Ndao'],
            ['id_province' => 19, 'city_name' => 'Sabu Raijua'],
            ['id_province' => 19, 'city_name' => 'Sikka'],
            ['id_province' => 19, 'city_name' => 'Sumba Barat'],
            ['id_province' => 19, 'city_name' => 'Sumba Barat Daya'],
            ['id_province' => 19, 'city_name' => 'Sumba Tengah'],
            ['id_province' => 19, 'city_name' => 'Sumba Timur'],
            ['id_province' => 19, 'city_name' => 'Timor Tengah Selatan'],
            ['id_province' => 19, 'city_name' => 'Timor Tengah Utara'],

            // Kalimantan Barat
            ['id_province' => 20, 'city_name' => 'Pontianak'],
            ['id_province' => 20, 'city_name' => 'Singkawang'],
            ['id_province' => 20, 'city_name' => 'Bengkayang'],
            ['id_province' => 20, 'city_name' => 'Kapuas Hulu'],
            ['id_province' => 20, 'city_name' => 'Kayong Utara'],
            ['id_province' => 20, 'city_name' => 'Ketapang'],
            ['id_province' => 20, 'city_name' => 'Kubu Raya'],
            ['id_province' => 20, 'city_name' => 'Landak'],
            ['id_province' => 20, 'city_name' => 'Melawi'],
            ['id_province' => 20, 'city_name' => 'Mempawah'],
            ['id_province' => 20, 'city_name' => 'Sambas'],
            ['id_province' => 20, 'city_name' => 'Sanggau'],
            ['id_province' => 20, 'city_name' => 'Sekadau'],
            ['id_province' => 20, 'city_name' => 'Sintang'],

            // Kalimantan Tengah
            ['id_province' => 21, 'city_name' => 'Palangka Raya'],
            ['id_province' => 21, 'city_name' => 'Barito Selatan'],
            ['id_province' => 21, 'city_name' => 'Barito Timur'],
            ['id_province' => 21, 'city_name' => 'Barito Utara'],
            ['id_province' => 21, 'city_name' => 'Gunung Mas'],
            ['id_province' => 21, 'city_name' => 'Kapuas'],
            ['id_province' => 21, 'city_name' => 'Katingan'],
            ['id_province' => 21, 'city_name' => 'Kotawaringin Barat'],
            ['id_province' => 21, 'city_name' => 'Kotawaringin Timur'],
            ['id_province' => 21, 'city_name' => 'Lamandau'],
            ['id_province' => 21, 'city_name' => 'Murung Raya'],
            ['id_province' => 21, 'city_name' => 'Pulang Pisau'],
            ['id_province' => 21, 'city_name' => 'Sukamara'],
            ['id_province' => 21, 'city_name' => 'Seruyan'],

            // Kalimantan Selatan
            ['id_province' => 22, 'city_name' => 'Banjarmasin'],
            ['id_province' => 22, 'city_name' => 'Banjarbaru'],
            ['id_province' => 22, 'city_name' => 'Balangan'],
            ['id_province' => 22, 'city_name' => 'Banjar'],
            ['id_province' => 22, 'city_name' => 'Barito Kuala'],
            ['id_province' => 22, 'city_name' => 'Hulu Sungai Selatan'],
            ['id_province' => 22, 'city_name' => 'Hulu Sungai Tengah'],
            ['id_province' => 22, 'city_name' => 'Hulu Sungai Utara'],
            ['id_province' => 22, 'city_name' => 'Kotabaru'],
            ['id_province' => 22, 'city_name' => 'Tabalong'],
            ['id_province' => 22, 'city_name' => 'Tanah Bumbu'],
            ['id_province' => 22, 'city_name' => 'Tanah Laut'],

            // Kalimantan Timur
            ['id_province' => 23, 'city_name' => 'Balikpapan'],
            ['id_province' => 23, 'city_name' => 'Bontang'],
            ['id_province' => 23, 'city_name' => 'Samarinda'],
            ['id_province' => 23, 'city_name' => 'Berau'],
            ['id_province' => 23, 'city_name' => 'Kutai Barat'],
            ['id_province' => 23, 'city_name' => 'Kutai Kartanegara'],
            ['id_province' => 23, 'city_name' => 'Kutai Timur'],
            ['id_province' => 23, 'city_name' => 'Mahakam Ulu'],
            ['id_province' => 23, 'city_name' => 'Paser'],
            ['id_province' => 23, 'city_name' => 'Penajam Paser Utara'],

            // Kalimantan Utara
            ['id_province' => 24, 'city_name' => 'Tarakan'],
            ['id_province' => 24, 'city_name' => 'Bulungan'],
            ['id_province' => 24, 'city_name' => 'Malinau'],
            ['id_province' => 24, 'city_name' => 'Nunukan'],
            ['id_province' => 24, 'city_name' => 'Tana Tidung'],

            // Sulawesi Utara
            ['id_province' => 25, 'city_name' => 'Manado'],
            ['id_province' => 25, 'city_name' => 'Bitung'],
            ['id_province' => 25, 'city_name' => 'Kotamobagu'],
            ['id_province' => 25, 'city_name' => 'Tomohon'],
            ['id_province' => 25, 'city_name' => 'Bolaang Mongondow'],
            ['id_province' => 25, 'city_name' => 'Bolaang Mongondow Selatan'],
            ['id_province' => 25, 'city_name' => 'Bolaang Mongondow Timur'],
            ['id_province' => 25, 'city_name' => 'Bolaang Mongondow Utara'],
            ['id_province' => 25, 'city_name' => 'Kepulauan Sangihe'],
            ['id_province' => 25, 'city_name' => 'Kepulauan Talaud'],
            ['id_province' => 25, 'city_name' => 'Minahasa'],
            ['id_province' => 25, 'city_name' => 'Minahasa Selatan'],
            ['id_province' => 25, 'city_name' => 'Minahasa Tenggara'],
            ['id_province' => 25, 'city_name' => 'Minahasa Utara'],

            // Sulawesi Tengah
            ['id_province' => 26, 'city_name' => 'Palu'],
            ['id_province' => 26, 'city_name' => 'Banggai'],
            ['id_province' => 26, 'city_name' => 'Banggai Kepulauan'],
            ['id_province' => 26, 'city_name' => 'Banggai Laut'],
            ['id_province' => 26, 'city_name' => 'Buol'],
            ['id_province' => 26, 'city_name' => 'Donggala'],
            ['id_province' => 26, 'city_name' => 'Morowali'],
            ['id_province' => 26, 'city_name' => 'Morowali Utara'],
            ['id_province' => 26, 'city_name' => 'Parigi Moutong'],
            ['id_province' => 26, 'city_name' => 'Poso'],
            ['id_province' => 26, 'city_name' => 'Sigi'],
            ['id_province' => 26, 'city_name' => 'Tojo Una-Una'],
            ['id_province' => 26, 'city_name' => 'Tolitoli'],

            // Sulawesi Selatan
            ['id_province' => 27, 'city_name' => 'Makassar'],
            ['id_province' => 27, 'city_name' => 'Palopo'],
            ['id_province' => 27, 'city_name' => 'Parepare'],
            ['id_province' => 27, 'city_name' => 'Bantaeng'],
            ['id_province' => 27, 'city_name' => 'Barru'],
            ['id_province' => 27, 'city_name' => 'Bone'],
            ['id_province' => 27, 'city_name' => 'Bulukumba'],
            ['id_province' => 27, 'city_name' => 'Enrekang'],
            ['id_province' => 27, 'city_name' => 'Gowa'],
            ['id_province' => 27, 'city_name' => 'Jeneponto'],
            ['id_province' => 27, 'city_name' => 'Luwu'],
            ['id_province' => 27, 'city_name' => 'Luwu Timur'],
            ['id_province' => 27, 'city_name' => 'Luwu Utara'],
            ['id_province' => 27, 'city_name' => 'Maros'],
            ['id_province' => 27, 'city_name' => 'Pangkajene Kepulauan'],
            ['id_province' => 27, 'city_name' => 'Pinrang'],
            ['id_province' => 27, 'city_name' => 'Sidenreng Rappang'],
            ['id_province' => 27, 'city_name' => 'Sinjai'],
            ['id_province' => 27, 'city_name' => 'Soppeng'],
            ['id_province' => 27, 'city_name' => 'Takalar'],
            ['id_province' => 27, 'city_name' => 'Tana Toraja'],
            ['id_province' => 27, 'city_name' => 'Toraja Utara'],
            ['id_province' => 27, 'city_name' => 'Wajo'],

            // Sulawesi Tenggara
            ['id_province' => 28, 'city_name' => 'Kendari'],
            ['id_province' => 28, 'city_name' => 'Bau-Bau'],
            ['id_province' => 28, 'city_name' => 'Bombana'],
            ['id_province' => 28, 'city_name' => 'Buton'],
            ['id_province' => 28, 'city_name' => 'Buton Utara'],
            ['id_province' => 28, 'city_name' => 'Kolaka'],
            ['id_province' => 28, 'city_name' => 'Kolaka Utara'],
            ['id_province' => 28, 'city_name' => 'Konawe'],
            ['id_province' => 28, 'city_name' => 'Konawe Utara'],
            ['id_province' => 28, 'city_name' => 'Muna'],
            ['id_province' => 28, 'city_name' => 'Muna Barat'],
            ['id_province' => 28, 'city_name' => 'Wakatobi'],

            // Gorontalo
            ['id_province' => 29, 'city_name' => 'Gorontalo'],
            ['id_province' => 29, 'city_name' => 'Bone Bolango'],
            ['id_province' => 29, 'city_name' => 'Gorontalo Utara'],
            ['id_province' => 29, 'city_name' => 'Gorontalo'],

            // Sulawesi Barat
            ['id_province' => 30, 'city_name' => 'Mamuju'],
            ['id_province' => 30, 'city_name' => 'Majene'],
            ['id_province' => 30, 'city_name' => 'Mamuju Tengah'],
            ['id_province' => 30, 'city_name' => 'Mamuju Utara'],
            ['id_province' => 30, 'city_name' => 'Polewali Mandar'],

            // Maluku
            ['id_province' => 31, 'city_name' => 'Ambon'],
            ['id_province' => 31, 'city_name' => 'Tual'],
            ['id_province' => 31, 'city_name' => 'Buru'],
            ['id_province' => 31, 'city_name' => 'Buru Selatan'],
            ['id_province' => 31, 'city_name' => 'Kepulauan Aru'],
            ['id_province' => 31, 'city_name' => 'Maluku Tengah'],
            ['id_province' => 31, 'city_name' => 'Maluku Tenggara'],
            ['id_province' => 31, 'city_name' => 'Maluku Tenggara Barat'],
            ['id_province' => 31, 'city_name' => 'Seram Bagian Barat'],
            ['id_province' => 31, 'city_name' => 'Seram Bagian Timur'],

            // Maluku Utara
            ['id_province' => 32, 'city_name' => 'Ternate'],
            ['id_province' => 32, 'city_name' => 'Tidore Kepulauan'],
            ['id_province' => 32, 'city_name' => 'Halmahera Barat'],
            ['id_province' => 32, 'city_name' => 'Halmahera Tengah'],
            ['id_province' => 32, 'city_name' => 'Halmahera Timur'],
            ['id_province' => 32, 'city_name' => 'Halmahera Selatan'],
            ['id_province' => 32, 'city_name' => 'Halmahera Utara'],
            ['id_province' => 32, 'city_name' => 'Pulau Morotai'],

            // Papua
            ['id_province' => 34, 'city_name' => 'Jayapura'],
            ['id_province' => 34, 'city_name' => 'Biak Numfor'],
            ['id_province' => 34, 'city_name' => 'Deiyai'],
            ['id_province' => 34, 'city_name' => 'Dogiyai'],
            ['id_province' => 34, 'city_name' => 'Intan Jaya'],
            ['id_province' => 34, 'city_name' => 'Jayapura'],
            ['id_province' => 34, 'city_name' => 'Jayawijaya'],
            ['id_province' => 34, 'city_name' => 'Keerom'],
            ['id_province' => 34, 'city_name' => 'Kepulauan Yapen'],
            ['id_province' => 34, 'city_name' => 'Lanny Jaya'],
            ['id_province' => 34, 'city_name' => 'Mamberamo Raya'],
            ['id_province' => 34, 'city_name' => 'Mamberamo Tengah'],
            ['id_province' => 34, 'city_name' => 'Mappi'],
            ['id_province' => 34, 'city_name' => 'Merauke'],
            ['id_province' => 34, 'city_name' => 'Mimika'],
            ['id_province' => 34, 'city_name' => 'Nabire'],
            ['id_province' => 34, 'city_name' => 'Nduga'],
            ['id_province' => 34, 'city_name' => 'Paniai'],
            ['id_province' => 34, 'city_name' => 'Pegunungan Bintang'],
            ['id_province' => 34, 'city_name' => 'Puncak'],
            ['id_province' => 34, 'city_name' => 'Puncak Jaya'],
            ['id_province' => 34, 'city_name' => 'Sarmi'],
            ['id_province' => 34, 'city_name' => 'Supiori'],
            ['id_province' => 34, 'city_name' => 'Tolikara'],
            ['id_province' => 34, 'city_name' => 'Waropen'],
            ['id_province' => 34, 'city_name' => 'Yahukimo'],
            ['id_province' => 34, 'city_name' => 'Yalimo'],


            // Papua Barat
            ['id_province' => 34, 'city_name' => 'Manokwari'],
            ['id_province' => 34, 'city_name' => 'Fakfak'],
            ['id_province' => 34, 'city_name' => 'Kaimana'],
            ['id_province' => 34, 'city_name' => 'Manokwari Selatan'],
            ['id_province' => 34, 'city_name' => 'Maybrat'],
            ['id_province' => 34, 'city_name' => 'Raja Ampat'],
            ['id_province' => 34, 'city_name' => 'Sorong'],
            ['id_province' => 34, 'city_name' => 'Sorong Selatan'],
            ['id_province' => 34, 'city_name' => 'Tambrauw'],
            ['id_province' => 34, 'city_name' => 'Teluk Bintuni'],
            ['id_province' => 34, 'city_name' => 'Teluk Wondama']
        ];

        DB::table('cities')->insert($cities);
    }
}
